from td_dashboard.views.maternal_eligibility import ListBoardView as MaternalEligibilityListboardView
from td_dashboard.views.maternal_subject import DashboardView as MaternalSubjectDashboardView
from td_dashboard.views.maternal_subject import ListboardView as MaternalSubjectListboardView
